<?php
/**
 * JP7's PHP Functions 
 * 
 * Contains the main custom functions and classes.
 * @author JP7
 * @copyright Copyright 2002-2008 JP7 (http://jp7.com.br)
 * @category JP7
 * @package Debug
 */
 
/**
 * Debug class, used to display filenames, processing time and display formatted SQL queries.
 *
 * @package Debug
 */
class Debug{
	/**
	 * Flag, it is <tt>TRUE</tt> if its displaying filenames or SQL queries.
	 * @var bool
	 */
	public $active;
	/**
	 * Flag indicating if filenames will be showed or not. Use $_GET['debug_filename'] to set it.
	 * @var bool 
	 */
	public $debugFilename;
	/**
	 * Flag indicating if the SQL queries will be showed or not. Use $_GET['debug_sql'] to set it.
	 * @var bool
	 */
	public $debugSql;
	/**
	 * In order to prevent errors with output and headers, set this variable <tt>TRUE</tt> after the headers are sent.
	 * @var bool 
	 */
	public $safePoint;
	/**
	 * Array containing the activity log for queries, filenames and their processing time.
	 * @var array 
	 */
	protected $_log;
	/**
	 * Stores the start time which is used to calculate the processing time. Use the method startTime() to set this variable.
	 * @var float|array
	 */
	protected $_startTime;
	/**
	 * Indicates the current template file loaded. Used on the showToolbar() method.
	 * @var bool
	 */
	protected $_templateFilename;
	/**
	 * Public Constructor, it checks the flags and settings, will do nothing if $c_jp7 is <tt>FALSE</tt>.
	 *
	 * @global bool
	 */	
	public function __construct() {
		global $c_jp7;
		if (!$c_jp7) return; // Only by Devs
		$this->startTime();
		// Debug - SQL
		$this->debugSql = $_GET['debug_sql'];
		// Debug - Filename
		if (isset($_GET['debug_filename'])) {
			setcookie('debug_filename', $_GET['debug_filename'], 0, '/');
			$_COOKIE['debug_filename'] = $_GET['debug_filename'];
		}
		if ($_COOKIE['debug_filename']) $this->debugFilename = $_COOKIE['debug_filename'];
		// Debug - Toolbar
		if (isset($_GET['debug_toolbar'])){
			setcookie('debug_toolbar', $_GET['debug_toolbar'], 0, '/');
			$_COOKIE['debug_toolbar'] = $_GET['debug_toolbar'];
		}
		// Setting it as active
		if ($_COOKIE['debug_toolbar'] || $this->debugSql || $this->debugFilename) $this->active = TRUE;
	}
	/**
	 * Starts recording the time spent on the code. When using more than one startTime(), the time will be displayed from the last to the first when getTime() is called.
	 *
	 * @return void
	 */	
	public function startTime() {
		$debug_mtime = explode(' ', microtime());
		$this->_startTime[] = $debug_mtime[1] + $debug_mtime[0];
	}
	/**
	 * Calculates and displays the time spent from the moment startTime() was called.
	 *
	 * @param bool Sets whether the time will be outputted or not.
	 * @return void
	 */	
	public function getTime($output = FALSE) {
		if (!count($this->_startTime)) return;
		$debug_mtime = explode(' ', microtime());
		// Retrieves and deletes the last value
		$debug_starttime = array_pop($this->_startTime);
		$debug_totaltime = round(($debug_mtime[0] + $debug_mtime[1] - $debug_starttime) * 1000);
		if ($output && $this->safePoint) echo '<div class="debug_msg">Processed in: ' . $debug_totaltime . 'ms.</div>';
		return $debug_totaltime;
	}
	/**
	 * Shows the filename if $safePoint and $debugFilename are <tt>TRUE</tt>. Adds the filename to $_log.
	 *
	 * @param string $filename Name of the file.
	 * @return string Returns the $filename value unchanged.
	 * @global string
	 */	
	public function showFilename($filename) {
		global $c_doc_root;
		if ($this->debugFilename && $this->safePoint) echo '<div class="debug_msg">' .  str_replace($c_doc_root, '/', $filename ) . '</div>';
		if ($this->active) {
			// Creates a new log entry for this file
			$this->addLog($filename, 'file');
		}
		return $filename;
	}
	/**
	 * Formats and displays an SQL query.
	 *
	 * @param string $sql SQL query to be formatted and displayed.
	 * @param bool $forceDebug If <tt>TRUE</tt> it will show the SQL even when $_GET['debug_sql'] is not set, the default value is <tt>FALSE</tt>.
	 * @param string Stylesheet on the box displayed. The default value is ''.
	 * @return void
	 */	
	public function showSql($sql, $forceDebug = FALSE, $style = '') {
		if (!$this->safePoint) return;
		if ($this->debugSql || $forceDebug) echo '<div class="debug_sql" style="' . $style . '">' . preg_replace(array('/(SELECT )/','/( FROM )/','/( WHERE )/','/( ORDER BY )/'),'<b>\1</b>', $sql, 1) . '</div>';
	}
	/**
	 * Formats and returns the backtrace.
	 *
	 * @param string $msgErro Error message (optional).
	 * @param string $sql SQL query which was executed (optional).
	 * @param array $backtrace Backtrace generated by debug_backtrace() (optional).
 	 * @return string Formatted HTML backtrace.
	 */	
	public function getBacktrace($msgErro = NULL, $sql = NULL, $backtrace = NULL) {
		if (!$backtrace) $backtrace = debug_backtrace();
		krsort($backtrace);
		$erroDetalhesArray = reset($backtrace);
		$S = '';
		if ($msgErro) $S .= '<strong style="color:red">       ERRO:</strong> ' . wordwrap($msgErro, 85, "\n")  . "\n";
		$S .= '<strong style="color:red">    ARQUIVO:</strong> ' . $erroDetalhesArray['file'] . "\n";	
		$S .= '<strong style="color:red">      LINHA:</strong> ' . $erroDetalhesArray['line'] . "\n";	
		$S .= '<strong style="color:red">        URL:</strong> ' . (($_SERVER['HTTPS'] == 'on') ? "https://" : "http://") . $_SERVER["HTTP_HOST"] . $_SERVER["REQUEST_URI"] . "\n";
		if ($_SERVER["HTTP_REFERER"]) $S .= '<strong style="color:red">    REFERER:</strong> ' . $_SERVER["HTTP_REFERER"] . "\n";	
		$S .= '<strong style="color:red">         IP:</strong> ' . $_SERVER["REMOTE_ADDR"] . "\n";
		$S .= '<strong style="color:red"> USER_AGENT:</strong> ' . $_SERVER['HTTP_USER_AGENT'] . "\n";
		if ($sql) $S .= '<strong style="color:red">        SQL:</strong> ' . preg_replace(array('/( FROM )/','/( WHERE )/','/( ORDER BY )/'), "\n" . '            \1', $sql)  . "\n";
		$S .= '<strong style="color:red">  BACKTRACE:</strong> ' . preg_replace(array('/( FROM )/','/( WHERE )/','/( ORDER BY )/'), "\n" . '                          \1', print_r($backtrace, TRUE));
		if (count($_POST)) $S .= '<strong style="color:red">       POST:</strong> ' . print_r($_POST, TRUE);	
		if (count($_GET)) $S .= '<strong style="color:red">        GET:</strong> ' . print_r($_GET, TRUE);
		if (count($_SESSION)) $S .= '<strong style="color:red">    SESSION:</strong> ' . print_r($_SESSION, TRUE);
		if (count($_COOKIE)) $S .= '<strong style="color:red">     COOKIE:</strong> ' . print_r($_COOKIE, TRUE);
		return '<pre style="background-color:#FFFFFF;font-size:11px;text-align:left;">' . $S . '</pre>';
	}
	/**
	 * Method to be used as default error handler with set_error_handler() function.
	 *
	 * @param $code Error type code, like E_STRICT, E_NOTICE and so on.
	 * @param $msgErro Error message.
	 * @return bool
	 */
	public function errorHandler($code, $msgErro) {
		if ($code == E_STRICT || $code == E_NOTICE || $code == E_DEPRECATED) return FALSE; // FALSE -> the default error handler will take care of it.
		if (error_reporting() == 0) return FALSE; // Programmer used @ so the error reporting value is 0.

		$backtrace = debug_backtrace();
		array_shift($backtrace);
		die(jp7_debug($msgErro, NULL, $backtrace));
	}
	/**
	 * Adds a log to the $_log array.
	 *
	 * @param string $value Value to be displayed.
	 * @param string $tag Tag which represents the type of data stored.
	 * @param int $time Time this proccess took in miliseconds, e.g. ammount of time a SQL query took to be executed.
 	 * @return void
	 */	
	public function addLog($value, $tag = 'log', $time = NULL) {
		$this->_log[] = array('tag' => $tag, 'value' => $value, 'time' => $time);
	}
	/**
	 * Returns the log array.
	 *
	 * @param string $value Value to be displayed.
	 * @param string $tag Tag which represents the type of data stored.
	 * @param int $time Time this proccess took in miliseconds, e.g. ammount of time a SQL query took to be executed.
 	 * @return array Returns the value of $_log.
	 */
	public function getLog() {
		return $this->_log;
	} 
	/**
	 * Sets the filename of the current template.
	 *
	 * @param string $filename Name of the current template file.
 	 * @return void
	 */
	public function setTemplateFilename($filename) {
		$this->_templateFilename = $filename;
	}
	/**
	 * Returns the filename of the current template.
	 *
 	 * @return string Name of the current template file.
	 */
	public function getTemplateFilename() {
		return $this->_templateFilename;
	}
	/**
	 * Displays current template, log data, and time for the page.
	 *
 	 * @return void
	 */
	public function showToolbar() {
		if (!$this->active || !$this->safePoint) return;
		
		if ($this->_templateFilename ) echo ('Template: ' . $this->_templateFilename );
		else echo('PHP_SELF: ' . $_SERVER['PHP_SELF']);
		
		jp7_print_r($this->_log);
		$this->getTime(TRUE);
	}
}
?>