<?php

class Jp7_Model_SiteSettingsTipo extends Jp7_Model_TipoAbstract {
	public $isSubTipo = true;
	
	/**
	 * Usado pelo helper _getColorField
	 * @var array
	 */
	private static $_dados = array();
	
	public $attributes = array(
		'id_tipo' => 'SiteSettings',
		'nome' => 'Configurações Gerais',
		'campos' => 'tit_1{,}Cabeçalho{,}{,}{,}{,}{,}0{,}{,}{,}{,}{,}{,}{,}{,}{,}tit_1{;}varchar_key{,}Título{,}{,}{,}{,}{,}0{,}{,}{,}{,}{,}{,}{,}{,}{,}header_title{;}varchar_1{,}Sub-Título{,}{,}{,}{,}S{,}0{,}{,}{,}{,}{,}{,}{,}{,}{,}header_subtitle{;}tit_2{,}Template{,}{,}{,}{,}{,}0{,}{,}{,}{,}{,}{,}{,}{,}{,}tit_2{;}special_1{,}Jp7_Model_SiteSettingsTipo::getTemplateFields{,}{,}{,}{,}{,}0{,}{,}{,}{,}{,}{,}Template{,}{,}{,}template_data{;}char_key{,}Mostrar{,}{,}{,}{,}{,}0{,}{,}{,}{,}{,}{,}{,}{,}{,}mostrar{;}',
		'children' => '',
		'arquivos_ajuda' => '',
		'arquivos' => '',
		'template' => '',
		'editpage' => '',
		'class' => '',
		'class_tipo' => '',
		'model_id_tipo' => 0,
		'tabela' => '',
		'unico' => 'S',
		'disparo' => 'Jp7_Model_SiteSettingsTipo::saveTemplateFields'
	);
		
	public static function getTemplateFields($campo, $value, $parte = 'edit') {
		switch ($parte) {
			case 'header':
				return $campo['label'];
				break;
			case 'list':
				// Retorna alguma coisa
				return $value;
				break;
			case 'edit':
				// Não sei porque ele coloca &quot;
				self::$_dados = unserialize(str_replace('&quot;', '"', $value));
				
				$campo['tipo'] = 'css_template';
				$campo['tipo_de_campo'] = 'select';
				$campo['separador'] = 'S';
				$campo['value'] = self::$_dados[$campo['tipo']];
				$campo['opcoes'] = array();
				
				foreach (glob(ROOT_PATH . '/_default/templates/*', GLOB_ONLYDIR) as $templateDir) {
					$relativeDir = str_replace(ROOT_PATH, '', $templateDir);
					$campo['opcoes'][$relativeDir] = basename($relativeDir);
				}
				$field = new InterAdminField($campo);
				echo $field->getHtml();
				
				self::_getColorField('header_background', 'Cabeçalho Fundo', '#ff0000');
				self::_getColorField('header_title_color', 'Cabeçalho Título', '#ff0000');
				self::_getColorField('header_subtitle_color', 'Cabeçalho Subtítulo', '#ff0000', true);
				
				self::_getColorField('menu_background', 'Menu Fundo', '#ff0000');
				self::_getColorField('menu_color', 'Menu Cor', '#ff0000');
				self::_getColorField('menu_active_background', 'Menu Ativo Fundo', '#ff0000');
				self::_getColorField('menu_active_color', 'Menu Ativo Cor', '#ff0000', true);
				
				self::_getColorField('content_background', 'Conteúdo Fundo', '#ff0000');
				self::_getColorField('content_title_color', 'Conteúdo Título', '#ff0000');
				self::_getColorField('content_subtitle_background', 'Conteúdo Subtítulo', '#ff0000');
				self::_getColorField('content_color', 'Conteúdo Texto', '#ff0000', true);
				break;
		}
	}
	
	protected static function _getColorField($nome_id, $nome, $default_value, $separador = '', $options = array()) {
		$campo = $options + array(
			'tipo' => 'css_' . $nome_id,
			'tipo_de_campo' => 'varchar',
			'nome' => $nome,
			'xtra' => 'cor',
			'value' => self::$_dados['css_' . $nome_id],
			'default' => $value,
			'separador' => $separador
		);
		
		$field = new InterAdminField($campo);
		echo $field->getHtml();
	}
	
	public static function saveTemplateFields() {
		global $id, $interadmin_id;
		if (!$id) {
			$id = $interadmin_id;
		}
		if ($id) {
			$tipo = InterAdminTipo::getInstance($_POST['id_tipo']);
			if ($registro = $tipo->getInterAdminById($id)) {
				$special_1 = array();
				foreach ($_POST as $key => $values) {
					if (startsWith('css_', $key) && !endsWith('_xtra', $key)) {
						$special_1[$key] = $values[0];
					}
				}
				$registro->updateAttributes(array(
					'special_1' => serialize($special_1)
				));
				
				self::$_dados = $special_1;
				self::_saveDynamicCss();
			}
		}
	}
	
	protected static function _saveDynamicCss() {
		global $c_interadminConfigPath ;
		$filename = $c_interadminConfigPath . 'dynamic.css';
		
		$content = '/*' . "\r\n" . 
			'NÃO EDITE ESTE ARQUIVO - Arquivo é gerado dinamicamente' . "\r\n" .
			'DO NOT EDIT THIS FILE - File is dynamically generated' . "\r\n" .
			'*/' .  "\r\n" .
			self::_getCssBase('header', array('header_background')) .
			self::_getCssBase('header-title', array('header_title_color')) .
			self::_getCssBase('header-subtitle', array('header_subtitle_color'));
		
		file_put_contents($filename, $content);
		
		/*
		if ($c_remote) {
			$query = 'remote_files=' . $filename .
				//'&redirect_1=http://' . $_SERVER['HTTP_HOST'] . '/interadmin/site/' . $s_interadmin_cliente . '/remote_files_cleanup.php' .
				'&file_path_src=' . 'http://' . $_SERVER['HTTP_HOST'] . '/interadmin/' . $c_interadminConfigPath .
				'&file_path_dst=' . $s_interadmin_cliente . '/' . $jp7_app . '/' .
				'&cliente=' . $s_interadmin_cliente;
			$remotePage = 'http://' . $config->server->host . '/' . $c_interadmin_remote_path . 'interadmin/site/aplicacao/remote_files.php?' . $query;
			$exportOk = @fopen($remotePage, 'r');
			if (!$exportOk) {
				$msg = 'Falha ao gravar backup.';
				if ($c_jp7) {
				  $msg .= '<br/> Página: ' . $remotePage;
				}
			}
		}
		*/
	}
	
	protected static function _getCssBase($base_id, $properties) {
		$css = '@base(' . $base_id . ') {' . "\r\n";
		foreach ($properties as $property) {
			if (endsWith('_background', $property)) {
				$cssProperty = 'background-color';
			} elseif (endsWith('_color', $property)) {
				$cssProperty = 'color';
			} else {
				continue;	
			}
			$css .= $cssProperty . ': ' . self::$_dados['css_' . $property] . ';' . "\r\n";
		}
		$css .= '}' . "\r\n";
		return $css;
	}
	
}