<?php

namespace Jp7\Interadmin\Field;

class Factory
{
    protected $namespace = 'Jp7\\Interadmin\\Field\\';
    /*
    protected $map = [
        'text' => [],
        'varchar' => [],
        'char' => [],
        'file' => [],
        'date' => [],
        'select' => [],
        'select_multi' => [],
        'special' => [],
        'tit' => [],
        'func' => []
    ];
    */
    /**
     * @param array[] $campos As generated by InterAdminTipo->getCampos()
     * @return Jp7_Interadmin_Field_Base[]
     */
    public function makeFromCampos(array $campos)
    {
        return array_map([$this, 'makeField'], $campos);
    }
    
    /**
     * @param array $campo As generated by InterAdminTipo->getCampos()
     * @return Jp7_Interadmin_Field_Base
     */
    public function makeField(array $campo)
    {
        // tipo_de_campo -> only used in a few specials / xtra_disabledfields
        $tipo = $campo['tipo_de_campo'] ? $campo['tipo_de_campo'].'_' : $campo['tipo'];
        $prefix = $this->getPrefix($tipo, $campo['xtra']);
        $class = $this->getFieldClass($prefix, $campo);
        return new $class($campo);
    }
    
    protected function getFieldClass($prefix, array $campo)
    {
        if ($prefix === 'special' || $prefix === 'func') {
            // Special as object implements FieldInterface
            // Special as callable should be deprecated in favor of object
            if (str_contains($campo['nome'], '\\')) {
                return $campo['nome'];
            }
        }
        return $this->namespace.studly_case($prefix).'Field';
    }
    
    /**
     * @param string
     */
    protected function getPrefix($tipo, $xtra)
    {
        $prefix = explode('_', $tipo)[0];
        if ($prefix === 'select') {
            if (starts_with($tipo, 'select_multi_')) {
                $prefix .= '_multi'; // SelectMultiField
                if ($campo['xtra'] === SelectMultiField::XTRA_RECORD_SEARCH) {
                    $prefix .= '_ajax'; // SelectMultiAjaxField
                }
            } else {
                if (in_array($xtra, [SelectField::XTRA_RECORD_AJAX, SelectField::XTRA_TYPE_AJAX])) {
                    $prefix .= '_ajax'; // SelectAjaxField
                } elseif (in_array($xtra, [SelectField::XTRA_RECORD_RADIO, SelectField::XTRA_TYPE_RADIO])) {
                    $prefix .= '_radio'; // SelectRadioField
                }
            }
        }
        return $prefix;
    }
}

/*
public static function getSelectTipoXtras()
{
    return ['S', 'ajax_tipos', 'radio_tipos'];
 * 
 * multi => S
 * 
 * 
 * Retorna os xtra dos campos do tipo special_ que armazenam tipos.
 *
 * @return array

public static function getSpecialTipoXtras()
{
    return ['tipos_multi', 'tipos'];
}
/**
 * Retorna os xtra dos campos do tipo special_ que armazenam múltiplos registros.
 *
 * @return array
public static function getSpecialMultiXtras()
{
    return ['registros_multi', 'tipos_multi'];
}
*/